### ISSUE TITLE
EnvFromSource is not parsed

### ISSUE THREAD

**Issue by Zevran** [Microsoft/kubernetes-cd-plugin#13]
Hi,

```EnvFromSource``` definition is not parsed, I dove into the dependencies and I have seen that kubernetes [models](https://github.com/fabric8io/kubernetes-model) definitions made by fabric8 are automatically generated and in the latest release of the package ```EnvFrom``` exists in the generated schemas.
It could come from the outdated version of kubernetes [client](https://github.com/fabric8io/kubernetes-client) which is in ```2.6.1``` whereas the latest is in ```3.0.1```.

Here is an example of a deployment with env vars profided by a config map :

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: emilevauge/whoami
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: whoami

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: whoami
data:
  ENV_FOO: "bar"
```

Hope it will help !

Regards
